File_Adapter: Create partial class placed in File_Adapter moved to File_Engine
BHoM/File_Toolkit pull request #135
Opened 2022-05-24 15:52 UTC by alelom

…le_Engine

   
### Issues addressed by this PR

Closes #134 

### Test files

### Changelog

### Additional comments

2022-11-22 17:15 UTC, FraserGreenroyd commented
@BHoMBot check serialisation

2022-12-14 18:09 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2022-12-14 18:20 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-12-14 19:25 UTC, alelom commented
Because BHoMBot is fragile, I will close this PR and reopen with a new one *wink wink*

2022-12-14 19:27 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-12-14 19:29 UTC, FraserGreenroyd requested changes

2022-12-14 19:29 UTC, FraserGreenroyd commented on File_Engine/Create/FSDirectory.cs
>          [Input("parentDirectory", "Path of parent Directory of the directory. You can also specify a string path.")]
```suggestion
```

2022-12-14 19:31 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2022-12-14 19:41 UTC, FraserGreenroyd commented
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

2022-12-14 19:52 UTC, FraserGreenroyd approved these changes
This has been reviewed in collaboration with @alelom for merge to beta.

2022-12-14 20:13 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2022-12-14 20:38 UTC, merged